export const movies = [
{
title: " Carros 2",
genre: " Ação ",
ageRating: livre,
synopsis: "O astro das corridas, Relâmpago McQueen, e o carro  guincho,Mate,viajam para disputar o primeiro Grand Prix Mundial, que irá revelar o carro mais veloz do planeta. Nessa jornada imperdível, Mate se envolve com um grupo de espionagem e vive grandes aventuras com seus amigos.",
trailer: "https://youtu.be/idQjr_xONE4?feature=shared"
},

{
title: "The Bad Guys: Haunted Heist.",
genre: "Ação",
ageRating: 10 anos,
synopsis: "The Bad Guys' Halloween night of thievery and crime turns into a night of terror when they come across a dangerous enemy of the supernatural kind that gives them a taste of their own medicine.",
trailer: "https://youtu.be/m8TFJ6GeWLE?feature=shared "
},

{
title: "Alerta Vermelho",
genre: " Ação ",
ageRating: 12 anos,
synopsis: "Um alerta vermelho da Interpol é emitido e o agente do FBI John Hartley assume o caso. Durante sua busca, ele se vê diante de um assalto ousado e é forçado a se aliar ao maior ladrão de arte da história, Nolan Booth, para capturar a ladra de arte mais procurada do mundo atualmente, Sarah Black.",
trailer: "https://youtu.be/5JQuYpBZarc?si=haonQaehUxcOPyrb"
},

{
title: "Jogos vorazes",
genre: "Ação",
ageRating: 14 anos,
synopsis: "Na região antigamente conhecida como América do Norte, a Capital de Panem controla 12 distritos e os força a escolher um garoto e uma garota, conhecidos como tributos, para competir em um evento anual televisionado. Todos os cidadãos assistem aos temidos jogos, no qual os jovens lutam até a morte, de modo que apenas um saia vitorioso. A jovem Katniss Everdeen, do Distrito 12, confia na habilidade de caça e na destreza com o arco, além dos instintos aguçados, nesta competição mortal..",
trailer: "https://youtu.be/7HDfIssATE4?si=cpJMAWA5IbY8PWWk 
"
},

{
title: "Logan",
genre: "Ação",
ageRating: 16 anos,
synopsis: "Em 2024, os mutantes estão em franco declínio, e as pessoas não sabem o real motivo. Uma organização está transformando as crianças mutantes em verdadeiras assassinas. Wolverine, cansado de tudo e a pedido de um cada vez mais enfraquecido Professor Xavier, precisa proteger a jovem e poderosa Laura Kinney, conhecida como X-23. Enquanto isso, o vilão Nathaniel Essex amplia seu projeto de destruição.",
trailer: "https://youtu.be/KPND6SgkN7Q?si=EFFjCrfXWhkv6DFV"
},

{
title: "WiFi Ralph: Quebrando a Internet",
genre: "Comédia",
ageRating: Livre,
synopsis: "Ralph, o mais famoso vilão dos videogames, e Vanellope, sua companheira atrapalhada, iniciam mais uma arriscada aventura. Após a gloriosa vitória no Fliperama Litwak, a dupla viaja para a world wide web, no universo expansivo e desconhecido da internet. Dessa vez, a missão é achar uma peça reserva para salvar o videogame Corrida Doce, de Vanellope. Para isso, eles contam com a ajuda dos cidadãos da internet e de Yess, a alma por trás do Buzzztube, um famoso website que dita tendências.",
trailer: "https://youtu.be/T73h5bmD8Dc?si=fOTOdMY3WzHqMPtg "
},

{
title: " O nome do sucesso",
genre: "Comédia",
ageRating: 10 anos,
synopsis: "Joy é uma jovem brilhante, mas sua vida pessoal é extremamente complicada. Divorciada e mãe de dois filhos, ela vive com seus pais e ex-marido, que mora no porão. Sua mãe, que vive no andar de cima e passa o dia todo assistindo a novelas, compartilha o espaço com seu pai, apesar de ter se divorciado há 17 anos. Criativa desde a infância, Joy inventa um esfregão de limpeza milagroso que se transforma em um fenômeno de vendas e faz dela uma das empreendedoras de maior sucesso dos Estados Unidos.",
trailer: "https://youtu.be/nw0lp7LzSvg?si=wOSE7Kjn33hPtLAx "
},

{
title: "A proposta",
genre: "Comédia",
ageRating: 12 anos,
synopsis: "Margaret Tate é uma poderosa editora de livros que corre o risco de ser deportada para o Canadá, seu país natal. Para poder permanecer em Nova York, ela diz estar noiva de Andrew, seu assistente. O jovem aceita ajudá-la, mas impõe algumas condições, entre elas ir para o Alasca e conhecer sua família excêntrica. Com um oficial da imigração sempre à espreita, Margaret e Andrew têm que seguir o plano de casamento apesar de diversos problemas",
trailer: "https://youtu.be/a5X3u5G3Z7k?si=03sIFfvkBytE83UE"
},

{
title: "Pronto, falei.",
genre: "Comédia",
ageRating: 14 anos,
synopsis: "Renato é um jovem tímido e inseguro, que expressa o que verdadeiramente pensa apenas por meio de e-mails. Ele escreve para o colega de trabalho, a namorada e os pais, mas não tem coragem de enviar as mensagens e deixa tudo na pasta de rascunhos. Um dia, sem nenhuma explicação, todos os seus e-mails arquivados são enviados e ele precisa enfrentar as terríveis consequências de ser quem realmente é.",
trailer: "https://youtu.be/fYuzAG-y9T4?feature=shared"
},

{
title: "Deadpool",
genre: "Comédia",
ageRating: 16 anos,
synopsis: "Wade Wilson é um ex-agente especial que passou a trabalhar como mercenário. Seu mundo é destruído quando um cientista maligno o tortura e o desfigura completamente. O experimento brutal transforma Wade em Deadpool, que ganha poderes especiais de cura e uma força aprimorada. Com a ajuda de aliados poderosos e um senso de humor mais desbocado e cínico do que nunca, o irreverente anti-herói usa habilidades e métodos violentos para se vingar do homem que quase acabou com a sua vida.",
trailer: "https://youtu.be/Q9X-bAE8KTc?si=BN-l-rTE23CMLGW-"
},

{
title: "Lessie ",
genre: "Drama",
ageRating: Livre,
synopsis: "A família Turner decide tentar uma nova vida no campo e no meio da viagem encontra Lassie, uma collie que depois de perder o dono em um acidente de carro, vê no pequeno e solitário Matt Turner um novo companheiro. A família decide adotar a cadela que é muito inteligente, e está sempre ajudando o novo amigo e seus familiares, que agora tentam criar ovelhas em uma fazenda.",
trailer: "https://youtu.be/VkwPGVUHg9E?si=K3MAMVO2G9BsqcZj "
},

{
title: "Quarto de guerra",
genre: "Drama",
ageRating: 10 anos,
synopsis: "O relacionamento de Elizabeth e Tony passa por uma crise. Um dia, Elizabeth conhece uma mulher que lhe ensina o poder da oração e, a partir daí, ela aposta todas as fichas na sua fé e em suas rezas, a fim de salvar seu casamento.",
trailer: "https://youtu.be/qpWd7jbeOKk?si=HJ5PGNF446FHoKF5 "
},

{
title: "O menino do Pijama listrado",
genre: "Drama",
ageRating: 12 anos,
synopsis: "Durante a Segunda Guerra Mundial, Bruno, um garoto de oito anos, e sua família saem de Berlim para residir próximo a um campo de concentração, onde seu pai acaba de se tornar comandante. Infeliz e solitário, ele vagueia fora de sua casa e certo dia encontra Shmuel, um menino judeu de sua idade. Embora a cerca de arame farpado do campo os separem, os meninos começam uma amizade proibida.",
trailer: "https://youtu.be/9U4NDpUw8dA?si=rvw3_7OeSe2GrmDE "
},

{
title: " A Rede Social",
genre: "Drama",
ageRating: 14 anos,
synopsis: "Em uma noite de outono em 2003, Mark Zuckerberg, estudante de Harvard e gênio da computação, começa a trabalhar em um novo conceito que acaba se transformando em uma rede social global conhecida como Facebook. Seis anos e 500 milhões de amigos mais tarde, Zuckerberg se torna o mais jovem bilionário da história com o sucesso de sua rede social. No entanto, a sua ascensão sem precedentes traz complicações legais e pessoais.",
trailer: "https://youtu.be/6VtX6przSlI?si=H8IST1l8WU9uZIRf"
},

{
title: "Empire State",
genre: "Drama",
ageRating: 16 anos,
synopsis: "Após ter sua entrada recusada na academia de polícia, Chris Potamitis acaba aceitando um emprego como segurança do famoso Empire State Building. Quando descobre que a segurança do lugar tem falhas, ele e um amigo planejam um roubo milionário nos cofres do local. Mas ambos terão que enfrentar dois problemas: a presença de uma máfia local, que já pretendia executar um plano semelhante, e a vigilância de um policial durão, que suspeita dos planos dos rapazes e passa a espiar as ações dos dois.",
trailer: "https://youtu.be/BgBire-4f1Q?si=WQ7wCOfxFo3mdZp2"
},

{
title: "Incríveis",
genre: "Animação",
ageRating: Livre,
synopsis: "Depois do governo banir o uso de superpoderes, o maior herói do planeta, o Sr. Incrível, vive de forma pacata com sua família. Apesar de estar feliz com a vida doméstica, o Sr. Incrível ainda sente falta dos tempos em que viveu como super-herói, e sua grande chance de entrar em ação novamente surge quando um velho inimigo volta a atacar. Só que agora ele precisa contar com a ajuda de toda a família para vencer o vilão.",
trailer: "https://youtu.be/uz5nMVBGDjk?si=G2_wpt_XwiFAk9GL"
},

{
title: "Rango",
genre: "Animação",
ageRating: 10 anos,
synopsis: "Um camaleão que viveu como um animal de estimação se encontra em uma crise de identidade. Rango se questiona sobre como se destacar quando é de sua natureza se camuflar. Acidentalmente, ele acaba em uma cidade de fronteira chamada Dirt e dá o primeiro passo em direção à transformação se tornando xerife. Embora inicialmente ele apenas tenha encenado, uma série de situações emocionantes e encontros escandalosos obrigam Rango a se tornar um verdadeiro herói.",
trailer: "https://youtu.be/LwSfIbBH8Pw?si=gynEfea-7d8kW5Gt"
},

{
title: "Uma história de amor e fúria ",
genre: "Animação",
ageRating: 12 anos ,
synopsis: "Um homem com quase 600 anos de idade acompanha a história do Brasil, enquanto procura a ressurreição de sua amada Janaína. Ele enfrenta as batalhas entre tupinambás e tupiniquins, antes dos portugueses chegarem ao país, e passa pela Balaiada e o movimento de resistência contra a ditadura militar, antes de enfrentar a guerra pela água em 2096.",
trailer: "https://youtu.be/V9BHvEHKRaM?si=RXdSnoTgWoQ5h5CR"
}

{
title: "Ghost in The shell",
genre: "Animação ",
ageRating: 14 anos,
synopsis: "Trata-se de um futuro onde o avanço tecnológico proporcionou à humanidade um modo de utilizar a tecnologia a seu favor, com implantes de peças robóticas e até mesmo a transferência da “alma” para um corpo cibernético",
trailer: "https://youtu.be/S38xw2a5IGE?si=PVJemH1l1hB1O3Wr"
},

{
title: "Death note ",
genre: "Animação",
ageRating: 16 anos,
synopsis: "A história centra-se em Light Yagami, um estudante do ensino médio que descobre um caderno sobrenatural chamado Death Note, no qual pode matar pessoas se os nomes forem escritos nele enquanto o portador visualizar mentalmente o rosto de alguém que quer assassinar.",
trailer: "https://youtu.be/NlJZ-YgAt-c?si=SZPmwrKENReVqSPy"
}

{
title: "zootopia",
genre: "Suspense",
ageRating: Livre,
synopsis: "Em uma cidade de animais, uma raposa falante se torna uma fugitiva ao ser acusada de um crime que não cometeu. O policial do local, o incontestável coelho, sai em sua busca.",
trailer: "https://youtu.be/prct6AB5tR8?si=prcxm7AbjhZ426Gn"
},

{
title: "Os Goonies",
genre: "Suspense",
ageRating: 12 anos,
synopsis: "Jovens encontram um misterioso mapa do tesouro e começam a seguir as pistas, entrando em um fabuloso mundo subterrâneo de passagens secretas, perigosas armadilhas e um antigo galeão pirata que esconde moedas de ouro.",
trailer: "https://youtu.be/eG2hX9Su7-w?si=KyafiH58GaNNAAaB"
}

{
title: " 12 horas",
genre: "Suspense",
ageRating: 12 anos,
synopsis: "Jill Parrish luta para reconstruir sua vida depois de um sequestro, aceitando um novo emprego e convidando sua irmã, Molly, para morar em sua casa. Mas ela desaparece, e Jill tem certeza que o mesmo homem que a raptou retornou para se vingar.",
trailer: "https://youtu.be/TLBRErNB5_g?si=W4JsNcQ4a13SNE9q"
},

{
title: " Obsessão Secreta ",
genre: "Suspense",
ageRating: 14 anos,
synopsis: "Jennifer acorda no hospital com amnésia e totalmente debilitada. Russel, seu marido, cuida dela, mas a moça suspeita que ele esteja escondendo alguma coisa sinistra",
trailer: "https://youtu.be/Nc6loZU3kjQ?si=kS0hZ65RaN5M7XUB "
}

{
title: "o filho protegido ",
genre: "Suspense",
ageRating: 16 anos,
synopsis: "A vida do pintor Lorenzo sai do controle quando ele começa a achar que sua esposa está tentando distanciá-lo de seu filho.",
trailer: "https://youtu.be/xlHvb0dVmgY?si=hhJaJM88sEvZxNmP"
},

{
title: "Goosebumps 2",
genre: "Terror",
ageRating: Livre,
synopsis: "Slappy usa seus poderes sobrenaturais para trazer terror na noite de Halloween com a ajuda do recém-ressuscitado Nikola Tesla, o famoso inventor sérvio-croata.",
trailer: "https://youtu.be/nQeOzfm-lps?si=3iQyEY-s-HuOEEwd "
}

{
title: "Coraline e o Mundo secreto",
genre: "Terror",
ageRating: 10 anos,
synopsis: " Enquanto explora sua nova casa à noite, a pequena Coraline descobre uma porta secreta que contém um mundo parecido com o dela, porém melhor em muitas maneiras. Todos têm botões no lugar dos olhos, os pais são carinhosos e os sonhos de Coraline viram realidade por lá. Ela se encanta com essa descoberta, mas logo percebe que segredos estranhos estão em ação: uma outra mãe e o resto de sua família tentam mantê-la eternamente nesse mundo paralelo.",
trailer: "https://youtu.be/X3Pc9emMSxk?feature=shared "
},

{
title: " Sobrenatural; A porta Vermelha",
genre: "Terror",
ageRating: 12 anos,
synopsis: "Josh Lambert segue para o leste para deixar seu filho, Dalton, na faculdade. Mas demônios reprimidos do passado voltam repentinamente para assombrar os dois.",
trailer: "https://youtu.be/e8-GtGmlu18?si=0va3tdK9DhdwZUN4 "
}

{
title: "Five Nights at Freddy's  O Pesadelo Sem Fim ",
genre: "Terror",
ageRating: 14 anos,
synopsis: "No Freddy Fazbear's Pizza, robôs animados fazem a festa das crianças durante o dia. Mas, quando chega a noite, eles se transformam em assassinos psicopatas.",
trailer: "https://youtu.be/h2lVX71L_3A?si=8dd9boxe-8x-DLlO "
},

{
title: "It - A Coisa ",
genre: "Terror",
ageRating: 16 anos,
synopsis: "Um grupo de crianças se une para investigar o misterioso desaparecimento de vários jovens em sua cidade. Eles descobrem que o culpado é Pennywise, um palhaço cruel que se alimenta de seus medos e cuja violência teve origem há vários séculos",
trailer: "https://youtu.be/dD264ZjfKlk?si=Z_PrHtGBdpHZR7RD "
}

{
title: " A.I. - Inteligência Artificial",
genre: "Ficção Científica",
ageRating: Livre,
synopsis: "David, o primeiro menino-robô programado para amar, é adotado por um funcionário da Cybertronics e sua esposa. No entanto, uma série de circunstâncias inesperadas dificulta a vida de David. Sem a total aceitação dos humanos ou das máquinas, o menino-robô embarca em uma jornada para descobrir seu verdadeiro mundo.",
trailer: "https://youtu.be/zQDgLoJkfFY?si=a36Ds67vVrvtY_GN "
},

{
title: "A Chegada ",
genre: "Ficção Científica",
ageRating: 10 anos,
synopsis: "Naves alienígenas chegaram às principais cidades do mundo. Com a intenção de se comunicar com os visitantes, uma linguista e um militar são chamados para decifrar as estranhas mensagens dos visitantes.",
trailer: "https://youtu.be/isWwUJf4KEA?si=147eSQG-ZsZgfSph "
}

{
title: " Transformers: O Lado Oculto da Lua",
genre: "Ficção Científica
",
ageRating: 12 anos,
synopsis: "Sam Witwicky e sua nova namorada, Carly, entram na briga quando os Decepticons renovam sua guerra contra os Autobots. Optimus Prime acredita que ressuscitar o antigo Transformer Sentinel Prime, ex-líder dos Autobots, pode levar à vitória. Essa decisão tem consequências devastadoras e a guerra parece pender a favor dos Decepticons, causando um conflito épico em Chicago.",
trailer: "https://youtu.be/VdENsMwf_CI?si=z6TeHg3sTfq-siO2"
},

{
title: "Pantera Negra ",
genre: "Ficção Científica",
ageRating: 14 anos,
synopsis: "Conheça a história de T'Challa, príncipe do reino de Wakanda, que perde o seu pai e viaja para os Estados Unidos, onde tem contato com os Vingadores. Entre as suas habilidades estão a velocidade, inteligência e os sentidos apurados.",
trailer: "https://youtu.be/wL4a4MafSjQ?si=BNZC33e6G2zNxIuI"
}

{
title: "Contatos de 4.º Grau",
genre: "Ficção Científica",
ageRating: 14 anos,
synopsis: "O desaparecimento de pessoas numa pequena cidade do Alasca desperta a atenção de um estudioso, qua acaba misteriosamente assassinado. Sua esposa, a psicóloga Abigail Tyler (Milla Jovovich), passa a associar as estranhas visões de seus pacientes traumatizados com o crime ocorrido e até então sem solução.",
trailer: "https://youtu.be/nZdHwCCwlJM?si=ucxj6W8vvc2rQOac "
},

{
title: "Festa no céu ",
genre: "Aventura",
ageRating: Livre,
synopsis: "Em San Ángel, no México, viviam Manolo, Maria e Joaquim, amigos desde a infância. Mesmo que suas vidas tenham tomado rumos diferentes - Maria foi para Europa, Joaquim ingressou na vida militar e Manolo se dedicou para ser toureiro - algo continuou igual: os dois ainda são apaixonados por Maria. Dividido entre cumprir as expectativas de sua família e seguir seu coração, Manolo viaja por mundos fantásticos e enfrenta seus maiores medos.",
trailer: "https://youtu.be/LUpkLYtz1OY?si=ZwD_ZH4he6PIqwdC "
}

{
title: "As Crônicas de Nárnia: A Viagem do Peregrino da Alvorada ",
genre: "Aventura",
ageRating: 10 anos,
synopsis: "Lucy, Edmund e Eustace se encontram com o rei Caspian e outros amigos e começam uma nova aventura a bordo do navio "O Peregrino da Alvorada" para encontrar os Lordes Desaparecidos de Telmar. Lá, encaram guerreiros, dragões, anões e tritões e tentam salvar a terra mágica.",
trailer: "https://www.adorocinema.com/filmes/filme-127922/"
},

{
title: "O impossível",
genre: "Aventura",
ageRating: 12 anos,
synopsis: "O casal Maria e Henry está aproveitando as férias de inverno na Tailândia junto com os três filhos pequenos. Mas em uma manhã, um tsunami de proporções devastadoras atinge o local, arrastando tudo o que encontra pela frente",
trailer: "https://www.youtube.com/watch?app=desktop&v=uzSkwWZNw-E"
}

{
title: " Enola Holmes",
genre: "Aventura",
ageRating: 14,
synopsis: "Enola Holmes só tem 16 anos, mas vai fazer de tudo para encontrar a mãe desaparecida, inclusive despistar o irmão Sherlock e ajudar um jovem lorde fugitivo.",
trailer: "https://youtu.be/rcV1I-397Wg?si=SNW-06px3cIsw4MJ "
},

{
title: "127 Horas",
genre: "Aventura",
ageRating: 16,
synopsis: "Ao explorar um cânion remoto em Utah, o alpinista e aventureiro Aron Ralston fica preso em uma fenda quando uma pedra cai. Nos cinco dias seguintes, Ralston examina sua vida e considera suas opções, as quais o levam a uma situação angustiante. Aron precisa tomar uma atitude para que possa se libertar e tentar voltar para a civilização.",
trailer: "https://youtu.be/SHQxpg4Lidg?si=xAssoPxPjMMlPIwy 
"
}
];
